### ISSUE TITLE
When installing from source on Ubuntu - gsmartcontrol-root does not execute the GUI

### ISSUE THREAD

**Issue by jkuj6** [ashaduri/gsmartcontrol#22]
When installing from repo's and clicking on the menu item **GSmartControl** it will prompt for a password, and it opens up the GUI.
But if i install from source, whether i click on the menu item, or whether i run gsmartcontrol-root in terminal it pops up with password prompt but when password is entered, the GUI never opens.
I get this if run `gsmartcontrol-root` from terminal:
```
Unable to init server: Could not connect: Connection refused
(gsmartcontrol:4088): Gtk-WARNING **: 19:23:32.852: cannot open display: :0
```

My issue is the same as these links:
https://forums.opensuse.org/showthread.php/556993-gsmartcontrol-doesn-t-start
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=963510

It only runs if i do sudo gsmartcontrol - but its obviously not supposed to be run like this.

Any solutions to this when installing from source?

Ubuntu 20.04

**Comment by ashaduri** [comment]
Hi,

The Debian package uses Polkit to run gsmartcontrol with elevated privileges. The `gsmartcontrol-root` script simply runs `pkexec gsmartcontrol` (`pkexec` is part of Polkit), and the `/usr/share/polkit-1/actions/org.gsmartcontrol.policy` file makes the system ask for admin privileges when `/usr/sbin/gsmartcontrol` is invoked using `pkexec`.

The most likely reason for your issue is that you are not installing these files to their proper paths. The distribution-specific paths are chosen by distribution maintainers at `configure` stage. Please make sure you use the same `configure` and `make install` lines as the distribution package.

I do not think the issues you're linking to are the same as this one. The openSUSE one is a user error. The Debian one is for an official package (which is working for you), not installed-from-source.

Also, please note that the `main` branch is not ready for general usage yet - the autotools-to-cmake port is quite new and is still lacking some functionality. The information above is for the stable `gsmartcontrol-gtk3` branch.

I'm going to close this issue for now as "invalid". If you still run into this problem after mirroring the distribution method of compilation and installation, I will reopen the issue.

Thanks
