### ISSUE TITLE
gsmartcontrol.exe Win64 v.1.1.4, portable | Unknown publisher

### ISSUE THREAD

**Issue by Ricky-Tigg** [ashaduri/gsmartcontrol#33]
**OS:** Windows | **edition:** 11; **version:** 21H2. **gsmartcontrol.exe Win64 version:** 1.1.4, as portable.

Hello. The publisher of this program appears to be unknown; probably to Microsoft.

![gsmartcontrol exe_execution](https://user-images.githubusercontent.com/26058215/169018279-4e70d755-c2b1-4231-8264-2b2605760963.png)

**Comment by ashaduri** [comment]
Thanks for the report.

This is a standard error that Windows displays when running exe files which were previously downloaded from the Internet (usually using an MS browser like Edge).

The proper way to "fix" this would be to buy a (time-limited) code signing certificate. Since this is not commercial software, I would like to avoid any continuous expenses. Especially since signing the exe files would have little to do with any actual security.

You can safely ignore this error if your GSmartControl download comes from gsmartcontrol.shaduri.dev, GitHub, or SourceForge.

I will close this issue as wontfix.
